---
title: "**Getting started**"
output:
  html_document:
    highlight: pygments
    theme: lumen
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
---

<style>

.space {
  margin-bottom: 2em;
}

h1 {
  padding-bottom: 0.5em;
}

h2 {
  padding-bottom: 0.5em;
}

p {
  font-size: 125%;
}

div.footer {
  position: fixed;
  background: white;
  bottom: 0;
  width: 100%;
  border-top: 0.1em solid grey;
}

div.footer p {
  padding-left: 0.5em;
}

</style>

----

<p style="font-size:200%; color:blue">Site under construction...</p>

<div class="space"></div>

# **Running PPGtk**

## Formatting data

Examples for each of the input files required by PPGtk are provided in the `example/` folder.

### Read count files

The read count files (**total reads** and **reference reads**) are tab delimited text files with one line per individual and one column per locus. Missing data are specified by a `-9` in the total reads matrix.

**Example read file**:

```
24  33  -9  ...
12   1   8  ...
.
.
.
2   14  -9  ...
```

### Error file

The error file is where the per-locus sequencing error is recorded. Each locus needs to have its own error value (even if they are all the same). You could also use, for example, the average Phred score for each locus as the error value.

**Example error file**:

```
0.001 0.012 0.0005  ...
```

## Configuration files

Example configuration files are provided in the `config-files/` folder in the PPGtk distribution.

## Starting an analysis

A PPGtk analysis can be run by typing the name of the executable, providing the name of the model you want to run, and providing the name of the configuration file that specifies all of the options for the chosen model.

```bash
# A test analysis
ppgtk -m freqs -c ../config-files/freqs.txt -q
```

<div class="space"></div>

 - Typing `ppgtk -h` will give a general help message for running the software.

 - Typing `ppgtk -m <model-name> -h` will give specific information on the chosen model.
 
 - The `-q` option suppresses output to the terminal.

<div class="footer">

<p style="position:relative"> [**Home**](http://pblischak.github.io/ppgtk) :: [**Installation**](http://pblischak.github.io/ppgtk/installation.html) :: [**Getting started**](http://pblischak.github.io/ppgtk/getting-started.html) ::  [**Manual**](http://pblischak.github.io/ppgtk/ppgtk-manual.html) </p>

</div>