---
title: '**PPGtk**'
output:
  html_document:
    highlight: pygments
    theme: lumen
#    toc: yes
#    toc_depth: 2
#    toc_float:
#      collapsed: no
---

<style>
.space {
  margin-bottom: 2em;
}

p {
  font-size: 125%
}

ul {
  font-size: 125%
}

</style>

### **the polyploid pop-gen toolkit**

<div class="space"></div>

----

<div class="space"></div>

<p style="font-size:200%; color:blue">Site under construction...</p>

<div class="space"></div>

<a href="https://github.com/pblischak/ppgtk" target="_blank">**View on GitHub**</a> :: <a href="https://github.com/pblischak/ppgtk/releases" target="_blank">**Download latest release**</a> :: <a href="https://hub.docker.com/r/pblischak/ppgtk/" target="_blank">**Get Docker image**</a>

<div class="space"></div>

**PPGtk is a suite of tools for the analysis of population genomic data collected for polyploid species.**

You can use the links above to view the source code, download the latest stable release, or obtain the software image for use with [Docker](https://docs.docker.com/).

Please note that PPGtk is currently in alpha-testing mode and is likely to change quite a bit while we continue with development. Because of this, we advise using the releases that we provide rather than the "master" GitHub branch.

<div class="space"></div>

### **Documentation**

 - [Installation](http://pblischak.github.io/ppgtk/installation.html): instructions for installing PPGtk from source, or for using the Docker image.
 - [Getting started](http://pblischak.github.io/ppgtk/getting-started.html): a quick guide to running an analysis with PPGtk.
 - [Manual](http://pblischak.github.io/ppgtk/ppgtk-manual.html): detailed documentation on the different options and methods implemented in PPGtk.
 - <a href="https://github.com/pblischak/ppgtk/issues" target="_blank">Report a bug</a>: if you find a bug in the code, please feel free to contact me (blischak.4@osu.edu) or file an issue on GitHub.
 - [Google Users Group](http://pblischak.github.io/ppgtk): **TO DO**.
