---
title: "**Installation**"
output:
  html_document:
    highlight: pygments
    theme: lumen
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
---

<style>

.space {
  margin-bottom: 2em;
}

h1 {
  padding-bottom: 0.5em;
}

h2 {
  padding-bottom: 0.5em;
}

h4 {
  padding-top: 0.5em;
}

p {
  font-size: 125%;
}

div.footer {
  position: fixed;
  background: white;
  bottom: 0;
  width: 100%;
  border-top: 0.1em solid grey;
}

div.footer p {
  padding-left: 0.5em;
}

</style>

----

<!-- <p style="font-size:200%; color:blue">Site under construction...</p> -->

<div class="space"></div>

PPGtk is written in C++ and needs to be compiled into in executable for you to be able to run it. If you are not familiar with the process of compiling programs from source, the section on **the PPGtk Docker image** should get you up and running without the need for you to compile any code. The only mandatory requirements for PPGtk are a C++ compiler and the [Boost](http://www.boost.org/) libraries. We have written sections of the code to take advantage of multithreading using [OpenMP](http://openmp.org/wp/) as well, but this is not a requirement to get the software to run.

#### **A quick aside on OpenMP**

In our experience, a good place to start when compiling PPGtk is to figure out what compiler you have and to see if it is OpenMP compliant. This simply means that it can compile code that has OpenMP multithreading commands. A good example of a commonly used, OpenMP compliant C++ compiler is **GNU g++**. Apple/Mac computers do not use GNU compilers, and the compilers that they do have are not OpenMP compliant. GNU compilers for Macs can be obtained, however, using Homebrew (Googling "GNU compilers for Mac" gives a slew of Stack Overflow discussions as well). Regardless of whether or not you use OpenMP, it is important that you use the same compiler for both Boost and PPGtk.

**Note**: the Docker image for PPGtk allows multithreading without the need for you to worry about compilers.

We have successfully compiled and run PPGtk with Boost and OpenMP on Mac OSX 10.9 and 10.10 (using GNU g++, not the Apple compilers), as well as Ubuntu 14.04 and 16.04 (comes with GNU g++). If you are working on a Windows computer, we suggest using the Docker image.

<div class="space"></div>

# **Compiling from source**

Below are basic instructions for each of the steps that are necessary for compiling PPGtk from source. The main issues that we had when working out how to get everything talking was linking errors (computer couldn't find the libraries the program needed to link to). The instructions below should hopefully help to prevent such headaches (but, as always, there is no guarantee).

## Getting Boost

The Boost libraries can be downloaded from [http://www.boost.org/](http://www.boost.org/). They provide detailed instructions for building the libraries in the ["Getting Started"](http://www.boost.org/doc/libs/1_61_0/more/getting_started/index.html) section of their website. However, we do not use many of the tools provided by Boost, so a full install is not necessary. Once you have the libraries downloaded, navigate to the Boost folder in a terminal (`cd path/to/boost_1_60_0`) and run the two commands below:

```bash
./bootstrap.sh --prefix=/usr/local --with-libraries=program_options
sudo ./b2 install
```

We have used Boost v1.59.0 and v1.60.0 successfully. More recent versions may work as well but you will have to test them to make sure.

## OpenMP

The OpenMP libraries are usually shipped with the compiler that you have so there are no additional files that you need to download. To compile PPGtk with OpenMP multithreading enabled, all you have to do is change a single line in the PPGtk Makefile (in the `src/` directory). Change the `OPENMP` variable from `no` to `yes`, like so:

```
# set this to 'yes' is you want multithreading. 'no' otherwise.
OPENMP=yes
```

## Obtaining PPGtk

Stable releases of PPGtk can be downloaded from GitHub via the [Releases](https://github.com/pblischak/ppgtk/releases) page. Once you have the software, navigate to the `src/` folder in a terminal, make the necessary changes to the Makefile for using OpenMP (see above), and then compile the program using `make`.

```bash
# Navigate to the 'src' folder
cd ppgtk-v0.1.0/src

# Make necessary changes to Makefile (set OPENMP=yes), then run next two line
make
sudo make install
```

The `make` command will compile the PPGtk executable and the `make install` command will copy it to `/usr/local/bin` so that you can run it from anywhere on your computer. We add `sudo` to the `make install` command because adding things to `/usr/local/bin` usually requires special permission (you'll be prompted to enter your password).

<div class="space"></div>

# **Docker image**

In an attempt to make PPGtk more accessible across operating systems, and to lessen the burden of installing dependencies (Boost and OpenMP), we have built an image of PPGtk using Docker, allowing users with the Docker software to more easily run our program. 

A full discussion of Docker is beyond the scope of this installation guide, but interested users can check out more details on the [Docker website](https://docs.docker.com/).

<div class="space"></div>

 > **Note**: getting Docker and using it to run PPGtk is done almost exclusively with commands issued in a terminal window. If you are unfamiliar/uncomfortable with using the command line, we suggest trying the following tutorials at <a href="http://swcarpentry.github.io/shell-novice/" target="_blank">Software Carpentry</a> and/or <a href="https://www.codecademy.com/learn/learn-the-command-line" target="_blank">Codecademy</a>.

<div class="space"></div>

## Downloading Docker

Start by downloading the [Docker Toolbox](https://www.docker.com/products/docker-toolbox). Run the the installation program and choose the defaults when prompted. The only thing you might want to change is which programs are actually installed. You really don't need **Kitematic**.

The main program that you will be using is the **Docker Quickstart Terminal**. Selecting this program will launch into a Unix-like terminal window, which is where you'll be executing all of the commands to obtain and run PPGtk.

## The PPGtk image

After launching the Docker Quickstart Terminal, getting the PPGtk image is straightforward. All you need to do is pull the image from Docker Hub using the following command:

```bash
docker pull pblischak/ppgtk
```

Now that you have the image, you can run it in a **Docker container** (a particular instance of an image). This will launch a bash shell running a minimal install of Ubuntu 14.04 with a percompiled version of PPGtk already installed. Interacting 

```bash
docker run -it pblischak/ppgtk
```

To test that everything is working in the container that you just launched, run this command:

```bash
ppgtk -m freqs -c ../config-files/freqs.txt
```

You should get a bunch of output printed to the screen that is reporting acceptance rates for the MCMC analysis that just ran.

## Linking a local folder

one of the files from your own computer are available within the Docker container 

```bash
docker run -it -v $(pwd):home/analysis pblischak/ppgtk
```

<div class="space"></div>

 > WARNING: do not link your entire `Home` folder or `root` directory because it will make the container huge.

The PPGtk image starts you off in the `src/` directory of the PPGtk software folder, so you will first need to move to the dedicated analysis folder. The commands below will get you into the proper directory, let you check and see if your files are present, and then run an analysis on your data with PPGtk.

```bash
# Change to the analysis/ directory in the home folder
cd home/analysis

# Check that your files are there
ls

# Then run your analysis (substitute the values you want)
ppgtk -m <model> -c <your-config-file>
```

You can suppress the printing of acceptance rates using the `-q` (quiet) flag.
 
<div class="space"></div>

## A multicore machine

```bash
docker-machine create --driver virtualbox --virtualbox-cpu-count <#cpus> <new-machine-name>
```

So, for example, if you wanted to create a new machine called `multicore` with access to 4 CPUs you would run:

```bash
docker-machine create --driver virtualbox --virtualbox-cpu-count 4 multicore
```

After you run this, part of the output will tell you to run this command:

```bash
docker-machine env multicore
```

This tells you how to set the Docker Environment variables to use the `multicore` machine that you just made.
To switch Docker from the `default` machine, just run:

```bash
eval $(docker-machine env multicore)
```
 
<div class="footer">

<p style="position:relative"> [**Home**](http://pblischak.github.io/ppgtk) :: [**Installation**](http://pblischak.github.io/ppgtk/installation.html) :: [**Getting started**](http://pblischak.github.io/ppgtk/getting-started.html) ::  [**Manual**](http://pblischak.github.io/ppgtk/ppgtk-manual.html) </p>

</div>